version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    #entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - nodenet
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet
  #nginx:
  #  image: nginx
  #  networks:
  #    - nodenet
  #  ports:
  #    - "8080:80"

networks:
  nodenet:
    driver: bridge
